### ISSUE TITLE
`docker-compose build` fails

### ISSUE THREAD

**Issue by afroraydude** [j-poff/skrypt#21]

**Comment by dfirebaugh** [comment]
I'm running docker on linux.  This is the error I'm receiving.

```WARNING: The MONGO_DATA_DIR variable is not set. Defaulting to a blank string.
WARNING: The MONGO_LOG_DIR variable is not set. Defaulting to a blank string.
WARNING: The NODE_ENV variable is not set. Defaulting to a blank string.
skrypt_db uses an image, skipping
Building skrypt_app
Step 1/9 : FROM mhart/alpine-node:6.14.3
 ---> 94eaef409975
Step 2/9 : RUN apt-get update && apt-get install -y build-essential && apt-get install -y python && npm install
 ---> Running in 34c7df7d98fd
/bin/sh: apt-get: not found
ERROR: Service 'skrypt_app' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y build-essential && apt-get install -y python && npm install' returned a non-zero code: 127
```

**Comment by afroraydude** [comment]
Its an issue between the `apt-get python` and the `npm install`, needs to `pip install bcrypt` or something similar perhaps?

**Comment by mvarrieur** [comment]
Added a PR to fix this, needed to change over the ubuntu `apt-get` commands to the alpine `apk` commands. Also alpine doesn't have a `build-essential` package so I switched it to `build-base`

**Comment by dlmarrero** [comment]
> Added a PR to fix this, needed to change over the ubuntu `apt-get` commands to the alpine `apk` commands. Also alpine doesn't have a `build-essential` package so I switched it to `build-base`

I was working on this issue as well, and I found that switching the package manager was not the only issue.  There were a few other problems that were preventing docker-compose from successfully starting the application.  I submitted a pull request with the fixes. #23
